import type { Metadata } from "next";
import "@/css/global.css";
import "@/css/utils.css"
import { Navigation } from "@/layout/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl_PL">
      <body
        className={` antialiased `}
      >
        {/* <Navigation /> */}
        {children}
      </body>
    </html>
  );
}
